title: cyka blyat
author: dmddjack
theme: minima
email: dmddjack@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The planetary orbit is not a circle with epicycles, but an ellipse.
  The Sun is not near the center but at a focal point of the elliptical orbit.
  Neither the linear speed nor the angular speed of the planet in the orbit is constant, but the area speed (closely linked historically with the concept of angular momentum) is constant.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
